// test subscription channel constant
const PUBSUB_NEW_SNIPPIT = "PUBSUB_NEW_SNIPPIT"
const PUBSUB_TEST_ALPHA = "PUBSUB_TEST_ALPHA"
const PUBSUB_NEW_MESSAGE = "PUBSUB_NEW_MESSAGE"

module.exports = { 
    PUBSUB_NEW_SNIPPIT, 
    PUBSUB_TEST_ALPHA,
    PUBSUB_NEW_MESSAGE
 }